### ISSUE TITLE
nginx conf for windows

### ISSUE THREAD

**Issue by softboy99** [bfwg/angular-spring-starter#1]
Hi,
i'm new to nginx, could you please give out the nginx conf for windows? your given one seems for linux. Thanks.

**Comment by bfwg** [comment]
Hi @softboy99 

The nginx configuration script is not only for linux, it works the same in Windows environment. You just need to put them in `nginx.conf` file. You can read more from http://nginx.org/en/docs/windows.html for how to setup nginx in Windows. 

If you don't want to use nginx at all, alternatively you can build the frontend project every time you make any changes to it and load the app from http://localhost:8080

**Comment by bfwg** [comment]
@softboy99 Have you solved your issue with Nginx?

**Comment by menostos** [comment]
Just use the cli proxy for such things https://github.com/angular/angular-cli/wiki/stories-proxy

**Comment by bfwg** [comment]
@menostos is totally right, thank you for the input!
