### ISSUE TITLE
Request with POST method

### ISSUE THREAD

**Issue by the-benito** [bfwg/angular-spring-starter#18]
Hi, and thanks for you project ! It's a good base for beginners.

I have a question: Is it possible to have an example with POST method ?
Because I try to use a POST request, but I have a 403 error "Invalid CSRF Token '9d9f[...]9c0' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.", and I don't know what can I do to solve this issue.
In your code, you declare a string variable "csrfToken" (file : api.service.ts) you don't use. Is it normal ?

Thanks !

**Comment by bfwg** [comment]
Hi @the-benito , you need to get the csrf token from the cookies and put it in the header of the post request.  
I'll add a POST request demo that uses `csrfToken` in the starter sometime soon.

Thanks for reporting this.

**Comment by bfwg** [comment]
Hi @the-benito , ignore what I said. We don't need `csrfToken` in the header. The csrf token is stored in the cookie. Angular will try to look for it and attach it to the request's header.
> Look for a cookie named XSRF-TOKEN on the current domain.
If that cookie is found, it reads the value and adds it to the request as the X-XSRF-TOKEN header.

![image](https://user-images.githubusercontent.com/12819525/28697520-47cd4ec2-72f1-11e7-97d8-c4fdf1bad959.png)
![image](https://user-images.githubusercontent.com/12819525/28697509-3d0015b0-72f1-11e7-8db2-36e0b1d17371.png)

**Comment by the-benito** [comment]
Hi @bfwg , thanks for your answer. 
I have had a problem because I couldn't find the X-XSRF-TOKEN created by Angular. just the XSRF-TOKEN cookie.
I found where the problem came from : I tried to use in “application.yml” a variable 
`server:
  contextPath: /api`
to put automatically this path in REST controllers. The problem is that the configuration also put this path in the cookie.

I don’t understand why, because in _AuthenticationSuccessHandler.java_, there is a method `authCookie.setPath( "/" );` used to set the path. 
It seems that this method doestn't have any effect (I tried with another path, for exemple : `authCookie.setPath( "/test" );` and it doesn’t work).  It’s strange.

**Comment by bfwg** [comment]
```java
        Cookie authCookie = new Cookie( TOKEN_COOKIE, ( jws ) );

	authCookie.setHttpOnly( true );

	authCookie.setMaxAge( EXPIRES_IN );

	authCookie.setPath( "/test" );

```
Hey @the-benito , those 4 lines worked for me, you need to go to `localhost:4200/test` to see the cookie with /test path.

**Comment by the-benito** [comment]
Hey @bfwg , sorry for my previous post, it was partially wrong.


I find a solution for my problem:
In _WebSecurityConfig.java_, it's possible to add:

`	private CsrfTokenRepository getCsrfTokenRepository() {
		CookieCsrfTokenRepository tokenRepository = CookieCsrfTokenRepository.withHttpOnlyFalse();
		tokenRepository.setCookiePath("/");
		return tokenRepository;
	}`

and to change in the function _configure(...)_, the line:

`.csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse()).and()`

with

`.csrfTokenRepository(this.getCsrfTokenRepository()).and()`


This thing permit to define directly the path of the cookie XSRF-TOKEN, and so to permit to use in “application.yml” a variable
`server: contextPath: /api` for example.

**Comment by bfwg** [comment]
Hi @the-benito , I had no idea `CsrfTokenRepository` was preventing “application.yml” variable to work. 
This is good to know and I'm glad it worked out for you.

Would you like to make a Pull Request and add that part in? I can add it if you are busy.
Thanks again.

**Comment by the-benito** [comment]
Hi @bfwg , after many tests, I found a problem.
The logout function doesn't work with this method, because when Spring Security tries to delete the cookie AUTH-TOKEN, the path contains "/api". So Angular doesn't delete this cookie.

![capture du 2017-07-31 22-16-52](https://user-images.githubusercontent.com/6204737/28796682-c962dc5e-763e-11e7-81a7-80f81f4e45ac.png)

We can see this with a breakpoint in Eclipse :
(file: org.springframework.security.web.authentication.logout.CookieClearingLogoutHandler) 
![capture du 2017-07-31 22-25-01](https://user-images.githubusercontent.com/6204737/28796784-2632d0d8-763f-11e7-8f23-1d6def31bad7.png)

So, I'm not sure it's the best thing to do to use a variable `server: contextPath: /api`
to put automatically a prefix "/api" in REST controllers. So, I think your code is better.

**Comment by bfwg** [comment]
Hi @the-benito , nice find! I guess we can leave the code as is util we found a better solution. Anyways, if you notice anything else, please feel free to open another issue/pr.😄
