### ISSUE TITLE
404 (Not Found)

### ISSUE THREAD

**Issue by softboy99** [bfwg/angular-spring-starter#2]
http://localhost:4200/auth/refresh 404 (Not Found)

**Comment by bfwg** [comment]
Hi, @softboy99 
If you are getting 404 for /auth or /API, that means you haven't properly setup nginx proxy settings yet. You are running the angular4 app on port 4200, and those two endpoints are on port 8080(spring boot).

**Comment by bfwg** [comment]
The project now uses proxy file from angular-cli instead of nginx.
