### ISSUE TITLE
Update frontend Angular version.

### ISSUE THREAD

**Issue by bfwg** [bfwg/angular-spring-starter#21]

**Comment by ershad1** [comment]
Please convert Http to HttpClient for service call. i am new to angular and learning that's why i am struggling to do that. But i am trying.

**Comment by bfwg** [comment]
@ershad1 I have upgraded Angular to version 5.0.2 and replaced Http with HttpClient.

**Comment by ershad1** [comment]
thanks a lot :)

**Comment by bfwg** [comment]
No problem.
