### ISSUE TITLE
Method with @PreAuthorize("hasRole('ADMIN')")  not work on postman or Soap Ui

### ISSUE THREAD

**Issue by NABEEL-AHMED-JAMIL** [bfwg/angular-spring-starter#32]
Hello fan.
How i hit this method in post men
https://github.com/bfwg/angular-spring-starter/blob/master/server/src/main/java/com/bfwg/rest/AuthenticationController.java#L65
-------------------------
When i hit postman button it show 403 error like below 
{
    "timestamp": 1508769665744,
    "status": 403,
    "error": "Forbidden",
    "exception": "org.springframework.security.access.AccessDeniedException",
    "message": "Access is denied",
    "path": "/api/changePassword"
}
--------------------------

**Comment by zhengye1** [comment]
Did you login and get the tokens and pass to header?

**Comment by NABEEL-AHMED-JAMIL** [comment]
yes i get the access token and pass into the header like "Basic acces-token"

**Comment by NABEEL-AHMED-JAMIL** [comment]
https://github.com/NABEEL-AHMED-JAMIL/Api-Test-with-swagger_2
this is link that i'm trying to doing example

**Comment by bfwg** [comment]
@NABEEL-AHMED-JAMIL 
The header doesn't look right. Please use
`"Authorization: Bearer xxxxxxxxxx"` where "xxxx" is your token.

**Comment by zhengye1** [comment]
I tried with soap ui, and I got following:
![image](https://user-images.githubusercontent.com/5428784/31907794-dff223ac-b802-11e7-9838-45c16e53631e.png)

**Comment by NABEEL-AHMED-JAMIL** [comment]
Basically "@PreAuthorize("hasRole('ADMIN')")" not work proper
i lot of time try but i get this message below in screenshot
[image: Inline image 1][image: Inline image 2]

**Comment by bfwg** [comment]
@zhengye1 
You need to obtain the CSRF token as well since the CSRF protection is enabled in the backend.
The CSRF can be found by looking into your cookie store and look for key `XSRF-TOKEN`.
![image](https://user-images.githubusercontent.com/12819525/31914504-c8d538e2-b7ff-11e7-88cf-831bcf820623.png)

**Comment by bfwg** [comment]
@NABEEL-AHMED-JAMIL 
I can't see your image.

**Comment by NABEEL-AHMED-JAMIL** [comment]
![screenshot 443](https://user-images.githubusercontent.com/24192325/31926081-0d4ec64a-b8a6-11e7-8d80-c55345b8822c.png)
![screenshot 444](https://user-images.githubusercontent.com/24192325/31926082-0d819872-b8a6-11e7-86f6-fff8241ff57f.png)

**Comment by bfwg** [comment]
@NABEEL-AHMED-JAMIL 

You are missing the CSRF token. The CSRF token can be found in your browser cookie store.

**Comment by NABEEL-AHMED-JAMIL** [comment]
Thanks Fan. One more think "is CSRF TOKEN" also be added in the header
like "Authentication Barer xxxx"

**Comment by bfwg** [comment]
The current implementation only supports passing csrf from a cookie.

**Comment by zhengye1** [comment]
Tried and I got ...
![image](https://user-images.githubusercontent.com/5428784/31944637-bd95016a-b89a-11e7-90ac-08ef5d784fff.png)


How I get the csrf token is in here
![image](https://user-images.githubusercontent.com/5428784/31944659-cf127f76-b89a-11e7-98f6-9bd1f3d0449a.png)

**Comment by NABEEL-AHMED-JAMIL** [comment]
well I first try on the "GET" method which is "PreAuthriz with "ADMIN"" it
give me the result. but when I try to hit the "Post and Delete" method
request it show same error
I just simple used like below for GET method
GET -----> http://localhost:8080/api/product/list
Header ----> [{"key":"Authorization","value":"","xxxxx":""}]
it work

**Comment by NABEEL-AHMED-JAMIL** [comment]
and other issue "logout method" when we call the api it show the "Success"
JSON but the user not login

**Comment by bfwg** [comment]
@NABEEL-AHMED-JAMIL @zhengye1 
GET requests does not require a CSRF token. I'll implementation a solution to disable CSRF protection when **no** Cookie is present(Hitting endpoint via postman). 

We have CSRF protection due to the fact that we are storing AUTH TOKEN in Cookie store. It will protect us against session riding attacks.

**Comment by NABEEL-AHMED-JAMIL** [comment]
Yes I now. I hit the ("DELETE", "POST", "PUT") request by using below
header add.

Authorization:  xxxxxx
X-XSRF-TOKEN:   xxxx
But one think i was notice that "X-XSRF-TOKEN" token value expire after
"ONE HIT" the request and need the new "Token value".
But I'm confuse suppose that you get the "X-XSRF-TOKEN" and place into the
header and get the value. IS this "Square" call or not tell me.

**Comment by NABEEL-AHMED-JAMIL** [comment]
I think we need the "interceptor" and "Cross Origin " in the back-end side

**Comment by NABEEL-AHMED-JAMIL** [comment]
and One think Fan I want "Work". These day. I'm free have no Job. I'm
Finding Job from the last 3 month. I work for you "Free or other option".
If you think....... then kindly replay me.
this is my email "nabeel.amd93@gmail.com" and sykpe "+923153817177"
hope you not mind on this post.

**Comment by bfwg** [comment]
@zhengye1 

Another way to get around CSRF token is to store the jwt token in localStorage instead of Cookie store. I have done that for another repository, here is the PR for it. https://github.com/bfwg/springboot-jwt-starter/pull/20
