### ISSUE TITLE
Weird behavior for options in ApiService.get method

### ISSUE THREAD

**Issue by zhengye1** [bfwg/angular-spring-starter#38]
Let said one of my API address is http://localhost:8080/api/search?city=Toronto, then in the front end code I use following:
```  getRestaurantByCity(city:String){
        const body=`city=${city}`;
       return this.apiService.get(this.configService.search_url, body);
}
```

But I got bad request, and I debug the serialize code and I realize it becomes this
![image](https://user-images.githubusercontent.com/5428784/33670490-33a8649c-da73-11e7-81cb-3e2c9235c81c.png)

Moreover, the link become  
![image](https://user-images.githubusercontent.com/5428784/33670652-93e83864-da73-11e7-8e66-0e528d4d3836.png)
 

Which is incorrect. The correct link should be ```http://localhost:4200/api/search?city=Toronto```

**Comment by bfwg** [comment]
Sorry for the late respond, have you tried with:
```javascript
       const arg= {
         city: city
       };
       return this.apiService.get(this.configService.search_url, arg);
```

**Comment by zhengye1** [comment]
It works now.
