### ISSUE TITLE
Add Signup page and logic after sign up

### ISSUE THREAD

**Issue by zhengye1** [bfwg/angular-spring-starter#39]
This should be a feature, and I am half way on implementation. 
I am thinking which one is better for following two:
-  Once user sign up successfully, login user automatically
Or 
- once user sign up successfully, route the user to login page and let user to login manually

What is your suggestion?

**Comment by bfwg** [comment]
I prefer to option one.
Here are more information that might be helpful for making a decision.
https://ux.stackexchange.com/questions/64385/where-should-we-redirect-users-to-after-sign-up

**Comment by zhengye1** [comment]
Almost done... but I realize weird behavior..

On the first time sign up, everything good. Then I log out and I sign up a new account, I got following:
![image](https://user-images.githubusercontent.com/5428784/34165588-b09b31c8-e4aa-11e7-8ec4-8fe231df151d.png)

But once I refresh the page or click the sign up button again.. It works fine..


In the backend code, In ```configure(HttpSecurity http)``` method of ```WebSecurityConfig.java```, I changed to 

```
  protected void configure(HttpSecurity http) throws Exception {
    http.csrf().ignoringAntMatchers("/api/login").ignoringAntMatchers("api/signup")
        .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse()).and()
        .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
        .exceptionHandling().authenticationEntryPoint(restAuthenticationEntryPoint).and()
        .addFilterBefore(jwtAuthenticationTokenFilter(), BasicAuthenticationFilter.class)
        .authorizeRequests().anyRequest().authenticated().and().formLogin().loginPage("/api/login")
        .successHandler(authenticationSuccessHandler).failureHandler(authenticationFailureHandler)
        .and().logout().logoutRequestMatcher(new AntPathRequestMatcher("/api/logout"))
        .logoutSuccessHandler(logoutSuccess).deleteCookies(TOKEN_COOKIE);
```

What I missing here?

**Comment by bfwg** [comment]
Logout will clean all your cookies(includes csrf). You will gain a new CSRF cookie once the page is refreshed. I'll review your PR later today/tomorrow. It's looking pretty solid. 😄
