### ISSUE TITLE
End point not reachable

### ISSUE THREAD

**Issue by jocnud** [bfwg/angular-spring-starter#40]
`/api/login` endpoint is not reachable when running the angular app in `ng serve` but `ng start` works.

Getting HTTP-404 on this endpoint `http://localhost:4200/api/login`

**Comment by bfwg** [comment]
Hi @jocnud , 

By `ng start` I assume you mean `npm start`.
If you look into https://github.com/bfwg/angular-spring-starter/blob/master/frontend/package.json#L7, you can see that `npm start` will add a proxy config flag to `ng serve`.
