### ISSUE TITLE
Where is the /api/login method in server application? 

### ISSUE THREAD

**Issue by TurkiNizar** [bfwg/angular-spring-starter#48]
I could not find any method in the rest controllers that has a **/api/login** mapping. Am I missing something ? 
Nor the /api/logout mapping indeed. 
@bfwg

**Comment by zhengye1** [comment]
In `WebSecurityConfig `class in `package com.bfwg.config`, it have following line in `configure() `method

`        .formLogin().loginPage("/api/login")`

This is the way we make custom login page, and let spring security to handle the login process.

Here is the spring security documentation for full explanation.
[](https://docs.spring.io/spring-security/site/docs/3.2.0.RELEASE/guides/form.html )
