### ISSUE TITLE
How AUTH-TOKEN cookie is saved automatically ?

### ISSUE THREAD

**Issue by BYH535** [bfwg/angular-spring-starter#51]
Hi, I am new to Angular and Spring boot applications, and actually I am studying  your project which helped me in learning a lot of things about the two technologies, so first of all I want to say thank you.

I have created a new project that has almost the same configuration of yours, but I noticed that the AUTH-TOKEN is not stored automatically in my browser, so I have decided to use [ngx-cookie-service](https://www.npmjs.com/package/ngx-cookie-service) in order to store it manually, this method solve my problem for now, but I need this token to be stored automatically.

Another thing is that when I try to build your app with ng-build, I can't find the dist folder generated.

**Comment by bfwg** [comment]
Hi, the `AUTH-TOKEN` is stored from the backend(Spring). Please take a look in [here](https://github.com/bfwg/angular-spring-starter/blob/58cb7654fd8c810be1774397d6408e1112547511/server/src/main/java/com/bfwg/security/auth/AuthenticationSuccessHandler.java#L46-L60)

The build folder and be found in `/server/src/main/resources/static`, and the configuration is in https://github.com/bfwg/angular-spring-starter/blob/58cb7654fd8c810be1774397d6408e1112547511/frontend/.angular-cli.json#L9

Thanks.
