### ISSUE TITLE
@PreAuthorize is giving me 401 in POST methods

### ISSUE THREAD

**Issue by BYH535** [bfwg/angular-spring-starter#52]
Hi, I have created a similar configuration of your app in an other one (Back and Front), after a successfully login, a service with POST method and **@PreAuthorize("hasRole('SPECIFICUSER')")** annotation is generating a 401 HTTP error.

Note that the **SPECIFICUSER** is the name of an authority, because I have 4 different authorities, and the consumer of the service that generate this problem is a user (Object implementing **UserDetails** interface) that has a list of authorities, one of them is an authority with name **ROLE_SPECIFICUSER**

Any ideas? Thank you !

**Comment by bfwg** [comment]
Hi, have you tried with other authorities, and do they work? 
Without dive into your code, I won’t be able to know the issue. I would suggest to ask this question on Stackoverflow because the question is more related to spring security.
