### ISSUE TITLE
Update to Spring Boot 2.1.0

### ISSUE THREAD

**Issue by romanoffs** [bfwg/angular-spring-starter#53]
When will you update spring boot to version 2.1.0?
Will this code work correctly with version 2.1.0?

**Comment by bfwg** [comment]
Hi @romanoffs , I would love to update spring to 2.1.0 on this project, but I have not found the chance to. Feel free to submit a PR if you want.

**Comment by CraigSDel** [comment]
Hi @bfwg, I have updated your project to Angular 7 and Spring 2

**Comment by bfwg** [comment]
Resolved in #54
