### ISSUE TITLE
Angular4 unit tests are failing.

### ISSUE THREAD

**Issue by bfwg** [bfwg/angular-spring-starter#6]
## Summary
The unit tests are broken in the frontend app folder.
If you run `npm run test` in the frontend folder, you can see the errors.

## Requirement
Resolve all unit test errors.

**Comment by zhengye1** [comment]
Checkout the version before my pull request and run `npm run test`, and the test are failing...
I will checkout my version and try to solve it this week

**Comment by bfwg** [comment]
Yes, it was failing before your pull request. 
Thanks @zhengye1 , I'll update the dependencies after your fix.

**Comment by bfwg** [comment]
Fixed in #7
