### ISSUE TITLE
ng build failed

### ISSUE THREAD

**Issue by zhengye1** [bfwg/angular-spring-starter#9]
I try to use `ng build`, no dist folder created

If I try to using `ng build --prod --bh /dist`, I got following error
![image](https://user-images.githubusercontent.com/5428784/27668610-42946f88-5c50-11e7-8f0f-d40b4675bce1.png)

**Comment by bfwg** [comment]
Looks like the Material2 pre-build css import is causing this issue.
https://github.com/bfwg/angular-spring-starter/blob/master/frontend/src/app/app.module.ts#L8

**Comment by bfwg** [comment]
Fixed in #12
